In [1]:
import pandas as pd

In [2]:

dict1 ={'Name': ['Priyang', 'Aadhya', 'Krisha', 'Vedant', 'Parshv','Mittal', 'Archana'],
'Marks': [98,89,99,87,90,83,99],
'Gender': ['Male', 'Female', 'Female', 'Male', 'Male','Female', 'Female']
       }

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

## Display top three rows

In [5]:
df.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

## Check the last three rows of the dataset

In [6]:
df.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

## Find Shape of Our Dataset (Number of Rows & Number of Columns)

In [7]:
df.shape

(7, 3)

In [8]:
print(f"Number or rows : {df.shape[0]} and Number of columns : {df.shape[1]}")

Number or rows : 7 and Number of columns : 3

## Get Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      str
dtypes: int64(1), str(2)
memory usage: 380.0 bytes

## Check null values in the dataset

In [10]:
df.isnull().sum()

Name      0
Marks     0
Gender    0
dtype: int64

## Get overall statistics about the dataset

In [11]:
df.describe()

           Marks
count   7.000000
mean   92.142857
std     6.491753
min    83.000000
25%    88.000000
50%    90.000000
75%    98.500000
max    99.000000

In [12]:
# here its calculating all of the stats for quatitative data only which is "marks" columns , if we want to include every column

df.describe(include="all")

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     Priyang        NaN  Female
freq          1        NaN       4
mean        NaN  92.142857     NaN
std         NaN   6.491753     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  98.500000     NaN
max         NaN  99.000000     NaN

## Find unique values from the Gender column

In [13]:
df["Gender"].unique()

<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

## Find the Number of Unique values from the Gender column

In [14]:
# To find the number of unique we can use method "nunique"

df["Gender"].nunique()

2

## Display Count of Unique Values in Gender Column

In [15]:
# Count of unique values ka mtlb hota hai, har value kitni kitni baar aayi hai

df["Gender"].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

## Find Total Number of Students Having Marks Between 90 To 100 (Inclusive) Using Between Method

In [16]:
bool_array = (df["Marks"] >= 90) & (df["Marks"] <= 100)

In [17]:
df[bool_array]["Name"]

0    Priyang
2     Krisha
4     Parshv
6    Archana
Name: Name, dtype: str

In [18]:
len(df[bool_array]["Name"])

4

In [19]:
# Using between method

bool_array = df["Marks"].between(90,100)

In [20]:
len(df[bool_array]["Name"])

4

## Find Average Marks

In [21]:
df["Marks"].mean()          # .min(), .max()

np.float64(92.14285714285714)

## Apply Method

In [22]:
# Using apply we can apply any  user defined function on the series or dataframe

def marks(x):
    return x / 2

In [23]:
df["Marks"].apply(marks)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

In [39]:
# lets make a new column for these half marks

df["Half marks"] = df["Marks"].apply(marks)

df

      Name  Marks  Gender  Half marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [25]:
# lambda function with apply

df["Marks"].apply(lambda x : x/2)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

In [26]:
# to get length of every name in the "Name" column

df["Name"].apply(len)

0    7
1    6
2    6
3    6
4    6
5    6
6    7
Name: Name, dtype: int64

## Map function

In [27]:
# we will perform encoding , will convert male to 1 and female to 0

df["Gender"].map({"Male" : 1, "Female" : 0})

0    1
1    0
2    0
3    1
4    1
5    0
6    0
Name: Gender, dtype: int64

In [40]:
df["Encoded Gender"] = df["Gender"].map({"Male" : 1, "Female" : 0})

In [41]:
df

      Name  Marks  Gender  Half marks  Encoded Gender
0  Priyang     98    Male        49.0               1
1   Aadhya     89  Female        44.5               0
2   Krisha     99  Female        49.5               0
3   Vedant     87    Male        43.5               1
4   Parshv     90    Male        45.0               1
5   Mittal     83  Female        41.5               0
6  Archana     99  Female        49.5               0

## Drop column(s)

In [38]:
df

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [44]:
# lets drop Half marks and Encoded Gender

df.drop(columns = ["Half marks","Encoded Gender"], inplace = True)

In [45]:
df

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

## Print name of the columns

In [47]:
df.columns            # .columns is an attribute of pandas DataFrame

Index(['Name', 'Marks', 'Gender'], dtype='str')

## Sort the DataFrame as per the marks column

In [50]:
# using sort_values

df.sort_values(by = "Marks")

      Name  Marks  Gender
5   Mittal     83  Female
3   Vedant     87    Male
1   Aadhya     89  Female
4   Parshv     90    Male
0  Priyang     98    Male
2   Krisha     99  Female
6  Archana     99  Female

## Display name and marks of the female students

In [70]:
bool_array = df["Gender"] == "Female"

In [71]:
df[bool_array][["Name","Marks"]]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99